name: commit-lint

on: [pull_request]

jobs:
  commit-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: bugbundle/commits@v1.1.0
        id: commits
      - run: echo ${{ steps.commits.outputs.major }}.${{ steps.commits.outputs.minor }}.${{ steps.commits.outputs.patch }}
