name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cs-fix:
    runs-on: ubuntu-24.04
    name: PHP-CS-Fixer
    container:
      image: php:8.1-cli

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
            git unzip zip \
            libzip-dev libpng-dev libjpeg-dev libfreetype6-dev

          docker-php-ext-configure gd --with-freetype --with-jpeg
          docker-php-ext-install gd zip

          curl -sS https://getcomposer.org/installer | php \
            -- --install-dir=/usr/local/bin --filename=composer

          composer install --prefer-dist --no-progress

      - name: Run PHP CS Fixer
        run: bin/php-cs-fixer fix --diff --dry-run


  tests:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    container:
      image: php:${{ matrix.php-version }}-cli

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y \
            git unzip zip \
            libpng-dev libjpeg-dev libfreetype6-dev libzip-dev

      - name: Install PHP extensions
        run: |
          docker-php-ext-configure gd --with-freetype --with-jpeg
          docker-php-ext-install gd zip

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php \
            -- --install-dir=/usr/local/bin --filename=composer

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: bin/phpunit --display-warnings --do-not-fail-on-warning


  tests-php84:
    runs-on: ubuntu-24.04
    container:
      image: php:8.4-cli

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y \
            git unzip zip \
            libpng-dev libjpeg-dev libfreetype6-dev libzip-dev

      - name: Install PHP extensions
        run: |
          docker-php-ext-configure gd --with-freetype --with-jpeg
          docker-php-ext-install gd zip

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php \
            -- --install-dir=/usr/local/bin --filename=composer

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: bin/phpunit --display-warnings --do-not-fail-on-warning