name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cs-fix:
    runs-on: ubuntu-24.04
    name: PHP-CS-Fixer

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: gd, simplexml, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v4

      - name: Run PHP CS Fixer
        run: bin/php-cs-fixer fix --diff --dry-run

  tests:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4', '8.5']

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd, simplexml, zip
          tools: composer:v2
          coverage: none

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        uses: ramsey/composer-install@v4

      - name: Run tests
        run: bin/phpunit --display-warnings --do-not-fail-on-warning
